### ISSUE TITLE
Local variable 'mesh_stats_file' referenced before assignment.

### ISSUE THREAD

**Issue by beliaev-maksim** [ansys/aedt-testing#191]
```
12.07.2022 19:20:12 (ERROR) Local variable 'mesh_stats_file' referenced before assignment.
Traceback (most recent call last):
  File "/lus01/mbeliaev/test_framework/venv/lib/python3.7/site-packages/aedttest/simulation_data.py", line 490, in <modu
le>
    main()
  File "/lus01/mbeliaev/test_framework/venv/lib/python3.7/site-packages/aedttest/simulation_data.py", line 474, in main
    designs_dict = extract_data(desktop, project_dir, project_name, design_names)
  File "/lus01/mbeliaev/test_framework/venv/lib/python3.7/site-packages/aedttest/simulation_data.py", line 234, in extra
ct_data
    design_dict = extract_design_data(
  File "/lus01/mbeliaev/test_framework/venv/lib/python3.7/site-packages/aedttest/simulation_data.py", line 307, in extra
ct_design_data
    design_dict[design_name]["mesh_name"][variation_name][setup] = mesh_stats_file
UnboundLocalError: Local variable 'mesh_stats_file' referenced before assignment.
12.07.2022 19:20:12 (ERROR) Local variable 'mesh_stats_file' referenced before assignment.
Traceback (most recent call last):
  File "/lus01/mbeliaev/test_framework/venv/lib/python3.7/site-packages/aedttest/simulation_data.py", line 490, in <modu
le>
    main()
  File "/lus01/mbeliaev/test_framework/venv/lib/python3.7/site-packages/aedttest/simulation_data.py", line 474, in main
    designs_dict = extract_data(desktop, project_dir, project_name, design_names)
  File "/lus01/mbeliaev/test_framework/venv/lib/python3.7/site-packages/aedttest/simulation_data.py", line 234, in extra
ct_data
    design_dict = extract_design_data(
  File "/lus01/mbeliaev/test_framework/venv/lib/python3.7/site-packages/aedttest/simulation_data.py", line 307, in extra
ct_design_data
    design_dict[design_name]["mesh_name"][variation_name][setup] = mesh_stats_file
UnboundLocalError: Local variable 'mesh_stats_file' referenced before assignment.
```

**Comment by beliaev-maksim** [comment]
@Samuelopez-ansys 
can you please fix the issue and cover it with unittest?
