### ISSUE TITLE
KeyError: ACConduction

### ISSUE THREAD

**Issue by beliaev-maksim** [ansys/aedt-testing#200]
```
14.07.2022 22:34:54 (ERROR) ACConduction
Traceback (most recent call last):
  File "/lus01/mbeliaev/test_framework/venv/lib/python3.7/site-packages/aedttest/simulation_data.py", line 491, in <modu
le>
    main()
  File "/lus01/mbeliaev/test_framework/venv/lib/python3.7/site-packages/aedttest/simulation_data.py", line 475, in main
    designs_dict = extract_data(desktop, project_dir, project_name, design_names)
  File "/lus01/mbeliaev/test_framework/venv/lib/python3.7/site-packages/aedttest/simulation_data.py", line 211, in extra
ct_data
    sweeps = app.existing_analysis_sweeps
  File "/lus01/mbeliaev/test_framework/venv/lib/python3.7/site-packages/pyaedt/application/Analysis.py", line 341, in ex
isting_analysis_sweeps
    setuptype = self.design_solutions.default_adaptive
  File "/lus01/mbeliaev/test_framework/venv/lib/python3.7/site-packages/pyaedt/application/design_solutions.py", line 54
0, in default_adaptive
    return self._solution_options[self.solution_type]["default_adaptive"]
KeyError: ACConduction

```

**Comment by Samuelopez-ansys** [comment]
Fixed issue in pyaedt: https://github.com/pyansys/pyaedt/pull/1404
