### ISSUE TITLE
KeyError: False

### ISSUE THREAD

**Issue by beliaev-maksim** [ansys/aedt-testing#201]
```
Traceback (most recent call last):
  File "/lus01/mbeliaev/test_framework/venv/lib/python3.7/site-packages/aedttest/simulation_data.py", line 491, in <modu
le>
    main()
  File "/lus01/mbeliaev/test_framework/venv/lib/python3.7/site-packages/aedttest/simulation_data.py", line 475, in main
    designs_dict = extract_data(desktop, project_dir, project_name, design_names)
  File "/lus01/mbeliaev/test_framework/venv/lib/python3.7/site-packages/aedttest/simulation_data.py", line 243, in extra
ct_data
    reports_dict = extract_reports_data(
  File "/lus01/mbeliaev/test_framework/venv/lib/python3.7/site-packages/aedttest/simulation_data.py", line 370, in extra
ct_reports_data
    data_dict = parse_rdat_file(report_file)
  File "/lus01/mbeliaev/test_framework/venv/lib/python3.7/site-packages/pyaedt/generic/report_file_parser.py", line 52, 
in parse_rdat_file
    si_unit_y = SI_UNITS[unit_system(y_data["TraceDataCol"]["Units"])]
KeyError: False

```

**Comment by boyang2022** [comment]
what is the unit in this case?

**Comment by Samuelopez-ansys** [comment]
Fixed issue in pyaedt: https://github.com/pyansys/pyaedt/pull/1404
