### ISSUE TITLE
pre-commit flake8-py3 failed

### ISSUE THREAD

**Issue by boyang2022** [ansys/aedt-testing#220]
@beliaev-maksim @Samuelopez-ansys 

AttributeError: 'EntryPoints' object has no attribute 'get'

error message:
flake8-py3...............................................................Failed
- hook id: flake8
- exit code: 1

Traceback (most recent call last):
  File "/home/runner/.cache/pre-commit/repoa18o316y/py_env-python3.7/bin/flake8", line 8, in <module>
    sys.exit(main())
  File "/home/runner/.cache/pre-commit/repoa18o316y/py_env-python3.7/lib/python3.7/site-packages/flake8/main/cli.py", line 22, in main
    app.run(argv)
  File "/home/runner/.cache/pre-commit/repoa18o316y/py_env-python3.7/lib/python3.7/site-packages/flake8/main/application.py", line 363, in run
    self._run(argv)
  File "/home/runner/.cache/pre-commit/repoa18o316y/py_env-python3.7/lib/python3.7/site-packages/flake8/main/application.py", line 350, in _run
    self.initialize(argv)
  File "/home/runner/.cache/pre-commit/repoa18o316y/py_env-python3.7/lib/python3.7/site-packages/flake8/main/application.py", line 330, in initialize
    self.find_plugins(config_finder)
  File "/home/runner/.cache/pre-commit/repoa18o316y/py_env-python3.7/lib/python3.7/site-packages/flake8/main/application.py", line 153, in find_plugins
    self.check_plugins = plugin_manager.Checkers(local_plugins.extension)
  File "/home/runner/.cache/pre-commit/repoa18o316y/py_env-python3.7/lib/python3.7/site-packages/flake8/plugins/manager.py", line 357, in __init__
    self.namespace, local_plugins=local_plugins
  File "/home/runner/.cache/pre-commit/repoa18o316y/py_env-python3.7/lib/python3.7/site-packages/flake8/plugins/manager.py", line 238, in __init__
    self._load_entrypoint_plugins()
  File "/home/runner/.cache/pre-commit/repoa18o316y/py_env-python3.7/lib/python3.7/site-packages/flake8/plugins/manager.py", line 254, in _load_entrypoint_plugins
    eps = importlib_metadata.entry_points().get(self.namespace, ())
AttributeError: 'EntryPoints' object has no attribute 'get'

flake8-py27..............................................................Passed
Table of Contents........................................................Passed
prettier.................................................................Passed
Error: The process '/opt/hostedtoolcache/Python/3.7.14/x64/bin/pre-commit' failed with exit code 1

**Comment by beliaev-maksim** [comment]
life is hard, try bumping flake version in pre commit
